### PR TITLE
Randomized pivot Quicksort [Java]

### LINKED ISSUE #435: Randomize pivot in quicksort [Java]
Median function is missing in java implementation of quicksort.
- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

### PR DESCRIPTION
**Pull request by Monal5031**
Fixes #435

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [x] I have read the [Contribution guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [x] I have followed the [coding guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#cs) for this project.
- [x] My code follows the [skeleton code structure](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#sample).
- [x] This pull request has a descriptive title. For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.

### CODE REVIEW

File: quick_sort/QuickSort.java [hunk 1]
```diff
@@ -1,9 +1,42 @@
...
+                return i;
+            } else {
+                return j;
+            }
+        }
+    }
+
     private static int partition(int[] arr, int start, int end) {
-        int pivot = arr[end];
+        int l = median(arr, start, end, (int)((start + end) / 2));
```
Comment (aashutoshrathi) [inline quick_sort/QuickSort.java]: Do we need typecasting ?

**Comment by Monal5031** [comment]
@aashutoshrathi Please review again.

File: quick_sort/QuickSort.java [hunk 2]
```diff
@@ -1,9 +1,42 @@
...
+    @param k: Middle index of array.
+    @return: Index of median of array at i, j, k.
+    */
+    private static int median(int[] arr, int i, int j, int k) {
+        if (arr[i] > arr[j] && arr[i] > arr[k]) {
+            if (arr[k] > arr[j]) {
+                return k;
+            } else {
+                return j;
+            }
```
Comment (aashutoshrathi) [inline quick_sort/QuickSort.java]: Make a function for this : 
```java
if (arr[k] > arr[j]) {
                return k;
            } else {
                return j;
            }
```

Comment (Monal5031) [reply quick_sort/QuickSort.java]: @aashutoshrathi Making a separate function for such small work wouldn't be good as it will increase the time of execution by extra function calls.

Comment (aashutoshrathi) [reply quick_sort/QuickSort.java]: But writing the same code for 3 times? Is it good? 😕

**Comment by Monal5031** [comment]
@aashutoshrathi Done.

File: quick_sort/QuickSort.java [hunk 3]
```diff
@@ -1,9 +1,38 @@
 public class QuickSort {
 
+    private static int compare(int[] arr, int i, int j) {
```
Comment (aashutoshrathi) [inline quick_sort/QuickSort.java]: Is `compare` a good name?
Or should it be `greaterIndex` or something relatable to what it is returning?

**Comment by singhpratyush** [comment]
@Monal5031: Why was this closed?

**Comment by Monal5031** [comment]
@singhpratyush Sorry sir, but it wasn't going anywhere so I closed it.

**Comment by singhpratyush** [comment]
I think that the code is good now and can be merged. Please repoen the PR.

**Comment by Monal5031** [comment]
@singhpratyush Thank you sir.
